name: llava
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.12.0
      - aiofiles==23.2.1
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - bitsandbytes==0.45.5
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepspeed==0.18.2
      - einops==0.6.1
      - einops-exts==0.0.4
      - exceptiongroup==1.3.1
      - fastapi==0.122.0
      - ffmpy==1.0.0
      - filelock==3.20.0
      - flash-attn==2.7.3
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==4.16.0
      - gradio-client==0.8.1
      - h11==0.14.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - latex2mathml==3.78.1
      - llava==1.2.2.post1
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - narwhals==2.12.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.18.0
      - pillow==10.4.0
      - platformdirs==4.5.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pynvml==13.0.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.29.0
      - ruff==0.14.7
      - safetensors==0.7.0
      - scikit-learn==1.2.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.46.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.50.0
      - svgwrite==1.4.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - timm==0.6.13
      - tokenizers==0.21.4
      - tomlkit==0.12.0
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - transformers==4.52.0
      - triton==3.2.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.23.0
      - wavedrom==2.0.3.post3
      - websockets==11.0.3
prefix: /mnt/ssd/anaconda3/envs/llava
